spring.application.name=fileSharingManagement


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cw_files_prj}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:7870}
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

logging.level.org.springframework.web=DEBUG

spring.security.oauth2.client.registration.google.client-id=${googleID:}
spring.security.oauth2.client.registration.google.client-secret=${googleSecret:}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}

spring.security.oauth2.client.registration.github.client-id=${gitHubID:}
spring.security.oauth2.client.registration.github.client-secret=${gitHubSecret:}
